name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        run: ls -a
      - name: output txt
        run: curl https://www.digitalocean.com/robot.txt. -output robot.txt
      - name: ls -l
        run: ls -l
      - name: cat robot.txt
        run: cat robot.txt