name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        run: ls -a
      - name: output txt
        run: curl https://www.digitalocean.com/robots.txt --output robots.txt
      - name: ls -l
        run: ls -l
      - name: cat robots.txt
        run: cat robots.txt
      - name: test
        run: |
          echo "Hello World"
          echo "Hello World"